security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

        app_client_provider:
            entity:
                class: App\Entity\Client
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\AppCustomAuthenticator
            custom_authenticators:
                - App\Security\AppCustomAuthenticator
            form_login:
                login_path: user_login
                check_path: user_login
                default_target_path: article_list
            logout:
                path: user_logout
               
                target: redirect_after_logout
                invalidate_session: true

        client:
            pattern: ^/client
            provider: app_client_provider
            entry_point: App\Security\AppCustomAuthenticator
            custom_authenticators:
                - App\Security\AppCustomAuthenticator
            form_login:
                login_path: client_login
                check_path: client_login
                default_target_path: page_client
            logout:
                 path: client_logout
                 invalidate_session: true
                 target: redirect_after_logout


               
