controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_first:
    path: /first
    controller: App\Controller\FirstController::index
article_index:
    path: /article
    controller: App\Controller\ArticleController::index
categorie_show:
    path: /categorie/{id}
    controller: App\Controller\CategorieController::show
    methods: [GET]
client_logout:
    path: /client/logout
    controller: App\Controller\ClientController::logout
redirect_after_logout:
    path: /redirect-after-logout
    controller: App\Controller\RedirectController::redirectAfterLogout
